# Generated by Django 3.0.8 on 2020-08-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idautor', models.IntegerField()),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('dni', models.IntegerField()),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
    ]
