# Generated by Django 3.0.8 on 2020-08-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editoriales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ideditorial', models.IntegerField()),
                ('nombre', models.CharField(max_length=40)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
    ]
