# Generated by Django 3.0.8 on 2020-08-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_editoriales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idpais', models.IntegerField()),
                ('nombre', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
    ]
